import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/common/Footer";
import { GoogleAnalytics } from "@next/third-parties/google"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />

        <main className="min-h-screen">{children}</main>
        <Toaster />
        <Footer />
      </body>
      <GoogleAnalytics gaId="G-HTM6GK8TE3" />
    </html>
  );
}
